version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productlayback2
      POSTGRES_DB: productlayback2
    ports:
      - '8083:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
